services:
  nginx:
    build: ./nginx
    container_name: chat-nginx
    ports:
      - "${NGINX_PORT:-3002}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - chat-backend-1
      - chat-backend-2
    networks:
      - chat-network

  chat-backend-1:
    build: .
    container_name: chat-backend-1
    expose:
      - "3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
    restart: unless-stopped
    networks:
      - chat-network

  chat-backend-2:
    build: .
    container_name: chat-backend-2
    expose:
      - "3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
    restart: unless-stopped
    networks:
      - chat-network

  redis:
    image: redis:alpine
    container_name: chat-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
networks:
  chat-network:
    driver: bridge
